/**
 * Created by wenja on 2017/6/17.
 */
// var Util = require('lib/Util');

function MainData() {
    this.ID = null;
    this.Reviewer = null;
    this.BUDistrict = null;
    this.OpportunityCode = null;
    this.Province = null;
    this.City = null;
    this.Site = null;
    this.ChineseName = null;
    this.EnglishName = null;
    this.PipelineStatus = null;
    this.ContractTerm = null;
    this.TargetRate = null;
    this.AnnualSales = null;
    this.CorporateAccountChinese = null;
    this.CorporateAccountEnglish = null;
    this.SalesRep = null;
    this.AssistCAMName = null;
    this.FollowingStatus = null;
    this.CTCBU = null;
    this.CTCSales = null;
    this.SalesType = null;
    this.FollowingStatusRemark = null;
    this.CompetitorCN = null;
    this.FirstCollaborationDate = null;
    this.EstimatedPCO = null;
    this.Remark = null;
    this.MarketClassification = null;
    this.RecordOwner = null;
};

MainData.prototype.constructTest = function () {
    this.Reviewer = 'Norman Li';
    this.BUDistrict = '东南向西北中';
    // this.OpportunityCode = ''; generated by express backend
    this.Province = '上海市';
    this.City = '浦东新区';
    this.Site = '金桥';
    this.ChineseName = '黄鹤';
    this.EnglishName = 'Huanghe';
    this.PipelineStatus = '>90Day';
    this.ContractTerm = '123年';
    this.TargetRate = '不确定';
    this.AnnualSales = 2333;
    this.CorporateAccountChinese = null;
    this.CorporateAccountEnglish = null;
    this.SalesRep = '葫芦娃';
    this.AssistCAMName = null;
    this.FollowingStatus = '123321';
    this.CTCBU = '不适用';
    this.CTCSales = null;
    this.SalesType = '基础四害';
    this.FollowingStatusRemark = null;
    this.CompetitorCN = '竞争者';
    this.FirstCollaborationDate = '2017-07-03';
    this.EstimatedPCO = 17;
    this.Remark = null;
    this.MarketClassification = '市场分类';
    this.RecordOwner = 'GLOBAL/wenja';
}

module.exports = MainData;