INSERT INTO GTWPEST.dbo.AssistCAMName (Detail) VALUES ('不适用(Null)');
INSERT INTO GTWPEST.dbo.AssistCAMName (Detail) VALUES ('Liang Chang （常亮） (20202429)');
INSERT INTO GTWPEST.dbo.AssistCAMName (Detail) VALUES ('Allen Tang （唐伟） (20224359)');
INSERT INTO GTWPEST.dbo.AssistCAMName (Detail) VALUES ('Lily Zhang （张忻） (20202261)');
INSERT INTO GTWPEST.dbo.AssistCAMName (Detail) VALUES ('Harry Zhou （周彬） (20202528)');
INSERT INTO GTWPEST.dbo.AssistCAMName (Detail) VALUES ('Shirley Li （李文青） (20201645)');
INSERT INTO GTWPEST.dbo.AssistCAMName (Detail) VALUES ('Tina Zhang （张彩瑜） (20202487)');
INSERT INTO GTWPEST.dbo.AssistCAMName (Detail) VALUES ('Camus Zhang （张彦超） (20202233)');
INSERT INTO GTWPEST.dbo.AssistCAMName (Detail) VALUES ('Alan Xu （徐祥贵） (20202120)');
INSERT INTO GTWPEST.dbo.AssistCAMName (Detail) VALUES ('Kevin Zhou （周立） (20202339)');
INSERT INTO GTWPEST.dbo.AssistCAMName (Detail) VALUES ('Liang He （何亮） (20223662)');
INSERT INTO GTWPEST.dbo.AssistCAMName (Detail) VALUES ('Matthew Shen （沈以强） (20221938)');