INSERT INTO GTWPEST.dbo.SalesType (Name) VALUES ('基础四害-Basic');
INSERT INTO GTWPEST.dbo.SalesType (Name) VALUES ('老鼠-Rodent');
INSERT INTO GTWPEST.dbo.SalesType (Name) VALUES ('蟑螂-Cockroach');
INSERT INTO GTWPEST.dbo.SalesType (Name) VALUES ('蚂蚁-Ant');
INSERT INTO GTWPEST.dbo.SalesType (Name) VALUES ('飞虫-flying insect');
INSERT INTO GTWPEST.dbo.SalesType (Name) VALUES ('仓储害虫-SPP');
INSERT INTO GTWPEST.dbo.SalesType (Name) VALUES ('蜥蜴-Lizard');
INSERT INTO GTWPEST.dbo.SalesType (Name) VALUES ('鸟类-Bird');
INSERT INTO GTWPEST.dbo.SalesType (Name) VALUES ('方案销售-Large Fly');
INSERT INTO GTWPEST.dbo.SalesType (Name) VALUES ('方案销售-Food Protect');
INSERT INTO GTWPEST.dbo.SalesType (Name) VALUES ('方案销售-Hotel Protect');
INSERT INTO GTWPEST.dbo.SalesType (Name) VALUES ('方案销售-Restaurant Protect');
INSERT INTO GTWPEST.dbo.SalesType (Name) VALUES ('捕蝇灯');
INSERT INTO GTWPEST.dbo.SalesType (Name) VALUES ('客户培训');