INSERT INTO GTWPEST.dbo.CTCBU (Name) VALUES ('不适用(Null)');
INSERT INTO GTWPEST.dbo.CTCBU (Name) VALUES ('Inst-机构部');
INSERT INTO GTWPEST.dbo.CTCBU (Name) VALUES ('FRS-超市部');
INSERT INTO GTWPEST.dbo.CTCBU (Name) VALUES ('TCD-纺织护理部');
INSERT INTO GTWPEST.dbo.CTCBU (Name) VALUES ('FB-食品饮料部');
INSERT INTO GTWPEST.dbo.CTCBU (Name) VALUES ('WPS-纳尔科水部门');
INSERT INTO GTWPEST.dbo.CTCBU (Name) VALUES ('QSR-快餐部');